# **Libraries - Numpy**

In [ ]:
"""
Numpy is a python library used for working with arrays.

it also has functions for working in domain of linear algebra, matrices etc..

NUMPY stands for Numerical Python.

the array object in numpy is called ndarray-n-dimensional array
"""

In [1]:
#no module called numpy - then execute
pip install numpy

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
print(np.__version__)

2.0.2


# **Dimensions in array**

In [ ]:
"""
a dimensions in arrays is one level of array  depth(nested array)

0-D Array
1-D Array
2-D Array
3-D Array
"""

In [6]:
#0-D Array or Scalars - are the dimensions in an array. Each value in an array is 0-D

import numpy as np
arr=np.array(30)
print(arr)

30


In [7]:
#1-D Array or Uni dimensional - an array that has 0-D array elements
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [8]:
#2-D Array  - an array that has 1-D arrays as its elements . used to represent matrix
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#3-D Array - an arrays that has 2-D array(matrices) as it elements
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)  #to find out the dimensions of array - ndim
print(b.ndim)

3
2


In [12]:
#Higher dimensional arrays - ndmin

x=np.array([1,2,3,4],ndmin=5)
print(x)
print(x.ndim)

[[[[[1 2 3 4]]]]]
5


# **Numpy Array Indexing**

In [16]:
a=np.array([1,2,3,4,5,6])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(a[2])

3


In [15]:
print(a[2]+a[4])

8


In [20]:
print('2nd element on 1st row: ',b[0,1])

2nd element on 1st row:  2


In [23]:
print('3rd element on 3rd row: ',b[2,2])

3rd element on 3rd row:  9


In [24]:
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
print(c[0,1,2])

6


In [26]:
print(c[1,0,1])

8
